---
title: "Survival Analysis of Chargeoff Data"
subtitle: |
  Samuel Nankervis, Evelyn Zhuang, Kay Ferrin\
  Southern Utah University\
  Fundamentals of Data Science\
  Dr. Rick Brown\
  April 13th, 2026
format: pptx
---

<!--
Comment about formatting:
From what I can tell, this is the general format for making the powerpoint slides. There's more info here:
https://quarto.org/docs/presentations/powerpoint.html
https://quarto.org/docs/reference/formats/presentations/pptx.html
Also make sure to close your powerpoint every time you render it or it won't render.
Anyway here's the little formatting guide I made while playing around with it.

#New Section with big title

## Slide Title (also makes a new slide)

- Bullet point

---

- Bullet point

---

::: {.incremental}

- This one appears first
- This one appears second

:::

---

```{r}
#| label: print something

print("Hello World")

```

## Look at this graph!

```{r}
#| label: plot something
plot(c(1,2,3), c(1,2,3))
```

-->

#New Section with big title

## Slide Title (also makes a new slide)

- Bullet point

---

- Bullet point

---

::: {.incremental}

- This one appears first
- This one appears second

:::

---

```{r}
#| label: print something

print("Hello World")

```

## Look at this graph!

```{r}
#| label: plot something
plot(c(1,2,3), c(1,2,3))
```
